{
  "language": "ruby",
  "os": [
    "linux"
  ],
  "dist": "xenial",
  "sudo": false,
  "cache": {
    "pip": true
  },
  "python": [
    "3.6",
    "3.7"
  ],
  "install": [
    "pip install git+https://github.com/rashidrao-pk/lime_stratified.git"
  ],
  "rvm": [
    "2.2",
    "jruby"
  ]
}

