dist: xenial
sudo: false
language: python
cache: pip
python:
  - "3.6"
  - "3.7"
# command to install dependencies
install:
  - pip install git+https://github.com/rashidrao-pk/lime_stratified.git
# command to run tests

language: ruby
rvm:
- 2.2
- jruby