name: Python Package Conda CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v2

      # Step 2: Set up Miniconda
      - name: Set up Miniconda
        uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
          python-version: 3.8  # Specify the Python version you need
          environment-file: github/workflows/environment.yml  # Specify the path to your environment.yml
          activate-environment: base

      # Step 3: Install additional dependencies
      - name: Install dependencies
        run: |
          conda env update --file github/workflows/environment.yml --name base
          conda install pytest  # or any other testing framework

      # Step 4: Run tests
      - name: Run tests
        run: |
          pytest  # Replace with your test command